version: '3.3'
services:
  rabbitmq:
    image: docker.io/bitnami/rabbitmq:4.0
    ports:
      - '4369:4369'
      - '5551:5551'
      - '5552:5552'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    environment:
#      - RABBITMQ_SECURE_PASSWORD=yes
      - RABBITMQ_LOGS=-
      - RABBITMQ_USERNAME=mac
      - RABBITMQ_PASSWORD=test
    volumes:
      - '/opt/container-volumes.dir/rabbitmq.dir:/bitnami/rabbitmq/mnesia'
